### ISSUE TITLE
買う

### ISSUE THREAD

**Issue by ujihisa** [akechi/kokoro#1]
たぶん$500くらいで買う
- CPU (Intel Core i5 Ivy Bridgeよさそう)
- RAM (8GB or more)
- HDD (3TBくらいいっとく?)
- マザボ (上記要件を満たすように)
- ケースと電源 (なるべく静音だといいなあ)

**Comment by supermomonga** [comment]
$600くらい行ってもOKです

**Comment by supermomonga** [comment]
それ以上は事前に聞いてもらえれば

**Comment by ujihisa** [comment]
買った

**Comment by ujihisa** [comment]
newegg.caで 04/25/2013 に購入した

11-119-261  CASE CM | RC-120A-KKN1 RT  
$49.99

13-128-526  MB GIGABYTE|GA-H61N-USB3 H61 1155 R 
$79.99

17-139-026  PSU CORSAIR|430W CX430 R  
$44.99

19-116-781  CPU INTEL|CORE I5 3330 3.0G 6M R  
$189.99

20-148-544  MEM 4Gx2|CRUCIAL BLS2KIT4G3D1609DS1 
$48.49

22-148-840  HDD 1T|ST ST1000DM003 7K 64M %  
$69.99

Total after tax: $562.93
