### ISSUE TITLE
メモリ増設計画

### ISSUE THREAD

**Issue by raa0121** [akechi/kokoro#2]
メモリが8GBでマイクラが辛かったりするらしいので、どうにかしたい

**Comment by ujihisa** [comment]
解決力

**Comment by raa0121** [comment]
いくらかお金を出す用意はあります
確か今のは @supermomonga さんがいくらか出したのかな？

**Comment by supermomonga** [comment]
500だか600ドルくらい

**Comment by supermomonga** [comment]
RAM16GBになれば色々と捗りそう

**Comment by raa0121** [comment]
ref. #1 を ReOpenしても良かったと思った

**Comment by ujihisa** [comment]
![](http://i.gyazo.com/ec4c4fd9e336eb09beee9a29ac28189a.png)

現在の構成力

**Comment by supermomonga** [comment]
benri

**Comment by raa0121** [comment]
Lingr にてメモリ増設で済むようでした

**Comment by supermomonga** [comment]
closeしてRAM増設計画のissue新しく立てますか？

**Comment by raa0121** [comment]
とりあえずここでいいんじゃないですかね 名前変えときます

**Comment by supermomonga** [comment]
たしかに

**Comment by raa0121** [comment]
@ujihisa @supermomonga これどうします？

**Comment by supermomonga** [comment]
とりあえず、やるとしたら幾らかかるのか、ですね

**Comment by ujihisa** [comment]
現在の物理構成をwikiにのせておきました https://github.com/akechi/kokoro/wiki#server-physical-info

あのマザボは

> Number of Memory Slots: 2×240pin
> Maximum Memory Supported: 16GB

で、いまマザボに入ってるメモリ8GBは

> (2 x 4GB) 240-Pin

つまり16GBにすることはできるけどその場合新しく8GBのRAMを2つ買う必要があることがわかった。

**Comment by ujihisa** [comment]
~~8GBのRAM x 2で16GBになるのを検索したところ G.SKILL社 (初耳) の$147 (+ tax + 送料) のやつが一番安いぽい。 http://www.newegg.ca/Product/Product.aspx?Item=N82E16820231489&cm_re=16gb_ram_240-pin-_-20-231-489-_-Product~~ ← DDR3 1600だからダメぽ

8GBのRAM x 2で16GBになるのを検索したところ Team Elite Plus社 (初耳) の$149.99 (+ tax + 送料) のやつが一番安いぽい。
http://www.newegg.ca/Product/Product.aspx?Item=N82E16820313427&cm_re=16gb_ram_1333-_-20-313-427-_-Product

**Comment by ujihisa** [comment]
購入done $173.58

**Comment by supermomonga** [comment]
:+1:
