### ISSUE TITLE
game鯖をCoreOS化

### ISSUE THREAD

**Issue by ujihisa** [akechi/kokoro#3]
必要なものはdockerとsshアクセスだけなので、Funtooである必要がなくなった。CoreOS化したい。

https://coreos.com/docs/running-coreos/platforms/qemu/

**Comment by ujihisa** [comment]
- ujihisa, supermomonga, thinca, raa0121 を作ってsudoerにしておきます。 鍵はraatooのものを流用
- 全員dockerのgroupにしておきます。

**Comment by supermomonga** [comment]
+1
